export type ProjectStatus = "live" | "vertical-slice" | "in-development" | "prototype" | "scaffold" | "concept"
export const STATUS_LABELS: Record<ProjectStatus,string> = { live:"Live", "vertical-slice":"Vertical Slice", "in-development":"In Development", prototype:"Prototype", scaffold:"Scaffold", concept:"Concept" }
export type ProjectCategory = "studio" | "client-work" | "community" | "cloud" | "security" | "personal-system" | "career" | "culture" | "learning" | "creative-tool" | "platform" | "research" | "game" | "worldbuilding" | "education" | "interactive"
export const CATEGORY_LABELS: Record<ProjectCategory,string> = { studio:"Creative Studio", "client-work":"Client Work", community:"Community", cloud:"Cloud Engineering", security:"Security Operations", "personal-system":"Personal Systems", career:"Career Tools", culture:"Culture", learning:"Learning", "creative-tool":"Creative Tools", platform:"Platform", research:"Research Lab", game:"Game", worldbuilding:"Worldbuilding", education:"Education", interactive:"Interactive Experience" }
export type HomepageSection = "work" | "building" | "lab" | "game-lab" | "bridge" | "stack-house"
export type MediaKind = "browser-capture" | "ui-preview" | "mobile-preview" | "wireframe" | "concept-art" | "prototype-video" | "game-still" | "architecture" | "worldbuilding" | "model"
export type MediaProvenance = "real" | "concept" | "prototype" | "placeholder"
export type MediaReadiness = "ready" | "pending" | "held"
export interface ProjectMedia { kind:MediaKind; provenance:MediaProvenance; readiness:MediaReadiness; label:string; alt:string; src?:string; note?:string; aspect?:"16:10"|"16:9"|"4:3"|"portrait"|"square" }
export interface ProjectLinks { live?:string; preview?:string; repo?:string; internal?:string }
export interface PortfolioProject {
  id:string; slug:string; name:string; category:ProjectCategory; status:ProjectStatus
  homepage?:{section:HomepageSection;order:number;featured?:boolean}
  hook:string; description:string; role?:string; links:ProjectLinks; tech:string[]
  caseStudy:"available"|"planned"|"none"; houseEligible:boolean; held?:boolean; archived?:boolean
  media:ProjectMedia[]; supporting?:ReadonlyArray<{name:string;label:string}>
}
const capture=(src:string,alt:string):ProjectMedia=>({kind:"browser-capture",provenance:"real",readiness:"ready",label:"LIVE SITE CAPTURE",alt,src,aspect:"16:10"})
const pending=(kind:MediaKind,label:string,alt:string,aspect:ProjectMedia["aspect"]="16:9",note?:string):ProjectMedia=>({kind,provenance:"placeholder",readiness:"pending",label,alt,aspect,note})
const p=(project:PortfolioProject)=>project

export const PORTFOLIO_PROJECTS: PortfolioProject[] = [
 p({id:"grey-key",slug:"grey-key-studios",name:"Grey Key Studios",category:"studio",status:"live",homepage:{section:"work",order:1,featured:true},hook:"Independent culture, built under one roof.",description:"A home for music, identity, experiments, and creative technology.",role:"Founder · Creative Director",links:{live:"https://www.greykeystudios.com/"},tech:[],caseStudy:"planned",houseEligible:true,media:[capture("/portfolio/grey-key-studios.png","Grey Key Studios live website")]}),
 p({id:"sbm",slug:"sbm-inc",name:"SBM Inc.",category:"client-work",status:"live",homepage:{section:"work",order:2},hook:"A credible digital front door for a community organization.",description:"A client-facing presence for an organization empowering BIPOC youth.",role:"Strategy · Design · Build",links:{live:"https://sbminc.org/"},tech:[],caseStudy:"planned",houseEligible:true,media:[capture("/portfolio/sbm-inc.png","SBM Inc. live website")]}),
 p({id:"zachardee",slug:"zachardee-holdings",name:"Zachardee Holdings",category:"client-work",status:"live",homepage:{section:"work",order:3},hook:"Profit with purpose. Integrity with impact.",description:"A shipped digital presence for a purpose-driven holding company.",links:{live:"https://www.zachardeeholdings.com/"},tech:[],caseStudy:"planned",houseEligible:true,media:[capture("/portfolio/zachardee-holdings.png","Zachardee Holdings live website")]}),
 p({id:"being-black-it",slug:"being-black-in-it",name:"Being Black In IT",category:"community",status:"live",homepage:{section:"work",order:4},hook:"Practical career guides for Black professionals in tech.",description:"A shipped community-facing guide and resource platform.",links:{live:"https://beingblackinit.com/"},tech:[],caseStudy:"planned",houseEligible:true,media:[capture("/portfolio/being-black-in-it.png","Being Black In IT live website")]}),
 p({id:"cloud-resume",slug:"cloud-resume",name:"Cloud Resume",category:"cloud",status:"live",homepage:{section:"work",order:5},hook:"The infrastructure is part of the story.",description:"A production resume platform built to make cloud engineering visible.",role:"Cloud Architect · Developer",links:{live:"https://resume.greykeystudios.dev/"},tech:[],caseStudy:"planned",houseEligible:true,media:[capture("/portfolio/cloud-resume.png","Cloud Resume live website")]}),
 p({id:"soc-os",slug:"soc-os",name:"SOC OS",category:"security",status:"live",homepage:{section:"work",order:6},hook:"Signal, response, and less operational noise.",description:"A focused operating layer for security work.",role:"Product · Engineering",links:{live:"https://soc.greykeystudios.dev/"},tech:[],caseStudy:"planned",houseEligible:true,media:[capture("/portfolio/soc-os.png","SOC live website")]}),
 p({id:"me-to-we",slug:"me-to-we",name:"Me To We",category:"community",status:"concept",hook:"Held from public display.",description:"Project record retained without publishing unfinished or unapproved material.",links:{},tech:[],caseStudy:"none",houseEligible:false,held:true,media:[{...pending("concept-art","PROJECT HELD","Me To We held project media","4:3"),readiness:"held"}]}),

 p({id:"lifeos",slug:"lifeos",name:"LifeOS",category:"personal-system",status:"vertical-slice",homepage:{section:"building",order:1,featured:true},hook:"A working slice of a personal operating system.",description:"A system in active development; detailed product media is pending.",links:{live:"https://life-os.greykeystudios.workers.dev/"},tech:[],caseStudy:"planned",houseEligible:true,media:[capture("/portfolio/lifeos.png","LifeOS live application"),pending("mobile-preview","MOBILE FLOW","LifeOS mobile preview","portrait")]}),
 p({id:"careeros",slug:"careeros",name:"CareerOS",category:"career",status:"in-development",homepage:{section:"building",order:2},hook:"Career decisions as a system, not a scramble.",description:"An active build with product details reserved for verified preview media.",links:{live:"https://career-os.greykeystudios.workers.dev/"},tech:[],caseStudy:"planned",houseEligible:true,media:[capture("/portfolio/careeros.png","CareerOS live application")]}),
 p({id:"diaspora-atlas",slug:"diaspora-atlas",name:"Diaspora Atlas",category:"culture",status:"in-development",homepage:{section:"building",order:3},hook:"A cultural map taking shape.",description:"An active build; imagery and product detail remain intentionally pending.",links:{live:"https://diaspora-atlas-app.greykeystudios.workers.dev/"},tech:[],caseStudy:"planned",houseEligible:true,media:[capture("/portfolio/diaspora-atlas.png","Diaspora Atlas live homepage")]}),
 p({id:"relearn",slug:"relearn",name:"ReLearn",category:"learning",status:"in-development",homepage:{section:"building",order:4},hook:"Return to what you once knew.",description:"An AI-assisted relearning and study-tool project in development.",links:{live:"https://rltest.greykeystudios.dev/"},tech:[],caseStudy:"planned",houseEligible:true,media:[capture("/portfolio/relearn.png","ReLearn live application")]}),
 p({id:"gk-plugin-suite",slug:"gk-plugin-suite",name:"GK Plugin Suite + GK Studio DAW",category:"creative-tool",status:"in-development",homepage:{section:"building",order:5},hook:"Tools for making sound inside the Grey Key world.",description:"A live preview home for the Grey Key plugin family, with the GK Studio DAW joining the same experience as it develops.",links:{live:"https://gks5.greykeystudios.workers.dev/"},tech:[],caseStudy:"planned",houseEligible:true,media:[capture("/portfolio/gk-plugin-suite.png","GK Plugin Suite live preview website")]}),
 p({id:"voiceover-lab",slug:"voiceover-lab",name:"Voiceover Lab",category:"creative-tool",status:"vertical-slice",homepage:{section:"building",order:6},hook:"A private practice room for finding the performance.",description:"A local-first studio where aspiring voice actors can choose or paste a script, record takes, listen back, review their work, and improve.",role:"Creator · Product Direction · AI-assisted Development",links:{live:"https://voiceoverlab.greykeystudios.workers.dev/",repo:"https://github.com/GreyKeyStudios/voiceoverlab"},tech:["Next.js","MediaRecorder","IndexedDB"],caseStudy:"planned",houseEligible:true,media:[capture("/portfolio/voiceover-lab.png","VOICE//ROOM guest web Practice dashboard")]}),
 p({id:"baseka",slug:"baseka",name:"Baseka",category:"platform",status:"scaffold",homepage:{section:"building",order:7},hook:"Foundation first.",description:"A scaffold-stage project with scope and media intentionally reserved.",links:{live:"https://baseka.greykeystudios.workers.dev/"},tech:[],caseStudy:"planned",houseEligible:true,media:[capture("/portfolio/baseka.png","Baseka live application")]}),
 p({id:"ahoden",slug:"ahoden-name-pending",name:"Ahoden — Name Pending",category:"platform",status:"scaffold",homepage:{section:"building",order:8},hook:"The project exists before the final name does.",description:"A scaffold-stage project whose public identity is still unresolved.",links:{live:"https://ahoden.greykeystudios.workers.dev/"},tech:[],caseStudy:"none",houseEligible:false,media:[capture("/portfolio/ahoden.png","Ahoden live application")]}),
 p({id:"suuru",slug:"suuru",name:"Suuru",category:"platform",status:"scaffold",homepage:{section:"building",order:9},hook:"An early system establishing its first durable shape.",description:"Scaffold-stage work with no fabricated product preview.",links:{live:"https://suuru.greykeystudios.workers.dev/"},tech:[],caseStudy:"none",houseEligible:true,media:[capture("/portfolio/suuru.png","Suuru live application")]}),

 p({id:"citizen-science",slug:"citizen-science",name:"Citizen Science",category:"research",status:"concept",homepage:{section:"lab",order:1},hook:"A question looking for an interface.",description:"An early lab investigation with concept media reserved.",links:{},tech:[],caseStudy:"none",houseEligible:false,media:[pending("wireframe","CONCEPT STUDY","Citizen Science concept study","4:3")]}),
 p({id:"chart-colleseum",slug:"chart-colleseum",name:"Chart Colleseum",category:"research",status:"prototype",homepage:{section:"lab",order:2},hook:"Data enters the arena.",description:"A lab prototype; the supplied spelling is retained until confirmed.",links:{},tech:[],caseStudy:"none",houseEligible:false,media:[pending("ui-preview","PROTOTYPE PREVIEW","Chart Colleseum prototype","4:3")]}),
 p({id:"deal-radar",slug:"deal-radar",name:"Deal Radar",category:"research",status:"scaffold",homepage:{section:"lab",order:3},hook:"A signal-finding experiment.",description:"A scaffold-stage lab project awaiting verified product media.",links:{},tech:[],caseStudy:"none",houseEligible:false,media:[pending("wireframe","EXPERIMENT SCAFFOLD","Deal Radar scaffold","4:3")]}),
 p({id:"crossword-builder",slug:"crossword-builder",name:"Crossword Builder",category:"research",status:"prototype",homepage:{section:"lab",order:4},hook:"A construction desk for wordplay.",description:"A lab prototype with its interface preview still pending.",links:{},tech:[],caseStudy:"none",houseEligible:false,media:[pending("ui-preview","PROTOTYPE PREVIEW","Crossword Builder prototype","4:3")]}),

 ...(["Cooley’s Revenge","MOLT","Pilot City","You’re It","The Room Is Negotiable","Corporate Espionage Sim","Life: A Horror Game","Kid at the Mall"] as const).map((name,index)=>p({id:["cooleys-revenge","molt","pilot-city","youre-it","room-negotiable","corporate-espionage-sim","life-horror-game","kid-at-mall"][index],slug:["cooleys-revenge","molt","pilot-city","youre-it","the-room-is-negotiable","corporate-espionage-sim","life-horror-game","kid-at-the-mall"][index],name,category:"game",status:"concept",homepage:{section:"game-lab",order:index+1,featured:index===0},hook:"A Grey Key game concept.",description:`${name} is represented as concept work; no gameplay or finished media is implied.${index===7?" Existing work may require recovery before it can be shown.":""}`,links:{},tech:[],caseStudy:"planned",houseEligible:true,media:[pending("concept-art","CONCEPT ART COMING",`${name} concept preview`,"16:9",index===7?"Existing work requires recovery before review":undefined)]})),
 p({id:"gk-backlot",slug:"gk-backlot",name:"GK Backlot",category:"worldbuilding",status:"prototype",homepage:{section:"game-lab",order:9},hook:"Reusable places waiting for stories.",description:"A supporting prototype and development system for Grey Key games.",links:{},tech:[],caseStudy:"planned",houseEligible:true,media:[pending("worldbuilding","BACKLOT ENVIRONMENT STUDY","GK Backlot environment preview","16:9")],supporting:[{name:"Motel",label:"ENVIRONMENT SLOT"},{name:"Self-storage facility",label:"ENVIRONMENT SLOT"},{name:"Apartment",label:"ENVIRONMENT SLOT"},{name:"Radio station",label:"ENVIRONMENT SLOT"}]}),

 p({id:"bridge-academy",slug:"bridge-academy",name:"Bridge Academy",category:"education",status:"concept",homepage:{section:"bridge",order:1,featured:true},hook:"Build the bridge.",description:"An architectural and educational study in access, practice, and the systems that help people cross into new work.",links:{},tech:[],caseStudy:"planned",houseEligible:true,media:[pending("architecture","ARCHITECTURAL STUDY · CONCEPT ART COMING","Bridge Academy architectural concept","16:9")]}),
 p({id:"stack-house",slug:"stack-house",name:"The Stack House",category:"interactive",status:"in-development",homepage:{section:"stack-house",order:1,featured:true},hook:"The other door.",description:"A real-time house built for exploration, story, and the work that does not fit in a grid.",links:{internal:"/house"},tech:[],caseStudy:"planned",houseEligible:true,media:[{kind:"model",provenance:"real",readiness:"ready",label:"INTERACTIVE HOUSE MODEL",alt:"The Stack House interactive 3D model",src:"/models/house-main-optimized.glb",aspect:"16:9"}]}),
]

export const projectsFor=(section:HomepageSection)=>PORTFOLIO_PROJECTS.filter(x=>!x.held&&!x.archived&&x.homepage?.section===section).sort((a,b)=>(a.homepage!.order-b.homepage!.order))
export const SHIPPED_PROJECTS=projectsFor("work"), BUILDING_PROJECTS=projectsFor("building"), LAB_PROJECTS=projectsFor("lab"), GAME_PROJECTS=projectsFor("game-lab")
export const BRIDGE_PROJECT=projectsFor("bridge")[0], STACK_HOUSE_PROJECT=projectsFor("stack-house")[0]

export type IdentityTransition = "shutter" | "prism" | "film-burn" | "scanline" | "double-exposure" | "ink" | "signal"
export type IdentityAsset = { src?:string; alt:string; placeholder:string }
export interface MusicIdentity { id:string;name:string;descriptor:string;transition:IdentityTransition;basePortrait:IdentityAsset;personaPortrait:IdentityAsset;artwork:IdentityAsset;audioSrc?:string;audioLabel:string;credits:string;projectTitles:string[];status:"identity-study"|"archive-ready";aside?:string }
const baseMichael:IdentityAsset={alt:"Michael Walton base portrait",placeholder:"BASE PORTRAIT / MICHAEL WALTON"}
export const MUSIC_IDENTITIES:MusicIdentity[]=[
 {id:"mr-e",name:"Mr. E",descriptor:"Alias study · sonic identity",transition:"shutter",basePortrait:baseMichael,personaPortrait:{alt:"Mr. E persona portrait",placeholder:"MR. E / PERSONA PORTRAIT"},artwork:{alt:"Mr. E project artwork",placeholder:"MR. E / PROJECT ARTWORK"},audioLabel:"Mr. E instrumental preview",credits:"Michael Walton · identity and music",projectTitles:["Builders Of The Future","Destination","Terra Gaia","1899 Waltz","Games On Channel 3"],status:"identity-study"},
 {id:"beautiful-uglies",name:"The Beautiful Uglies",descriptor:"Group identity · visual study",transition:"prism",basePortrait:baseMichael,personaPortrait:{alt:"The Beautiful Uglies group portrait",placeholder:"THE BEAUTIFUL UGLIES / GROUP PORTRAIT"},artwork:{alt:"The Beautiful Uglies project artwork",placeholder:"THE BEAUTIFUL UGLIES / PROJECT ARTWORK"},audioLabel:"The Beautiful Uglies instrumental preview",credits:"Michael Walton · creative direction",projectTitles:["Soundtrack For An Unmade Film","Midnight Blues","A Series Of Failures"],status:"identity-study"},
 {id:"adwo-nyumbani",name:"Adwo Nyumbani",descriptor:"Alias study · character system",transition:"film-burn",basePortrait:baseMichael,personaPortrait:{alt:"Adwo Nyumbani persona portrait",placeholder:"ADWO NYUMBANI / PERSONA PORTRAIT"},artwork:{alt:"Adwo Nyumbani project artwork",placeholder:"ADWO NYUMBANI / PROJECT ARTWORK"},audioLabel:"Adwo Nyumbani instrumental preview",credits:"Michael Walton · identity and music",projectTitles:["Calm Home","A Lamenting Waltz In C# Minor","Abstract Waltz","The Golden Stool"],status:"identity-study",aside:"Yes, this is still Michael. The aliases have begun organizing."},
 {id:"walton-grey",name:"Walton Grey",descriptor:"Alias study · tonal system",transition:"scanline",basePortrait:baseMichael,personaPortrait:{alt:"Walton Grey persona portrait",placeholder:"WALTON GREY / PERSONA PORTRAIT"},artwork:{alt:"Walton Grey project artwork",placeholder:"WALTON GREY / PROJECT ARTWORK"},audioLabel:"Walton Grey instrumental preview",credits:"Michael Walton · identity and music",projectTitles:["Private Karate","Plastic Horizons","Liminal Spaces (working title)","Cardboard Portraits","Lighthouse"],status:"identity-study"},
 {id:"mic-titan",name:"Mic Titan",descriptor:"Alias study · performance identity",transition:"double-exposure",basePortrait:baseMichael,personaPortrait:{alt:"Mic Titan persona portrait",placeholder:"MIC TITAN / PERSONA PORTRAIT"},artwork:{alt:"Mic Titan project artwork",placeholder:"MIC TITAN / PROJECT ARTWORK"},audioLabel:"Mic Titan instrumental preview",credits:"Michael Walton · identity and music",projectTitles:["3 Remix Projects","2–3 albums of older unreleased music"],status:"identity-study"},
 {id:"chno",name:"CHNO",descriptor:"Alias study · signal identity",transition:"signal",basePortrait:baseMichael,personaPortrait:{alt:"CHNO persona portrait",placeholder:"CHNO / PERSONA PORTRAIT"},artwork:{alt:"CHNO project artwork",placeholder:"CHNO / PROJECT ARTWORK"},audioLabel:"CHNO instrumental preview",credits:"Michael Walton · identity and music",projectTitles:["Catalog TBD"],status:"identity-study"},
]
export const MUSIC_CREDITS=["Uncle Fart","The Bobbie Backfat Band","Lemon Ice","Samon","Uncle Arctica","The Broken Shortcuts","Night Movers","Kief Swette"].map((name,index)=>({id:`credit-${index}`,name,descriptor:"Additional identity",artwork:{alt:`${name} identity artwork`,placeholder:`${name.toUpperCase()} / IDENTITY ART`} as IdentityAsset}))
