export type ProjectStatus = "live" | "vertical-slice" | "in-development" | "prototype" | "scaffold" | "concept"
export const STATUS_LABELS: Record<ProjectStatus,string> = { live:"Live", "vertical-slice":"Vertical Slice", "in-development":"In Development", prototype:"Prototype", scaffold:"Scaffold", concept:"Concept" }
export type ProjectCategory = "studio" | "client-work" | "community" | "cloud" | "security-portfolio" | "personal-system" | "career" | "culture" | "learning" | "creative-tool" | "gaming-system" | "health" | "personal-finance" | "trading-literacy" | "support-tool" | "research" | "game" | "worldbuilding" | "education" | "interactive"
export const CATEGORY_LABELS: Record<ProjectCategory,string> = { studio:"Creative Studio", "client-work":"Client Work", community:"Community", cloud:"Cloud Engineering", "security-portfolio":"Security Portfolio", "personal-system":"Personal Systems", career:"Career Tools", culture:"Culture", learning:"Learning", "creative-tool":"Creative Tools", "gaming-system":"Local Gaming System", health:"Health and Fitness", "personal-finance":"Personal Finance", "trading-literacy":"Trading Literacy", "support-tool":"Support Tools", research:"Research Lab", game:"Game", worldbuilding:"Worldbuilding", education:"Education", interactive:"Interactive Experience" }
export type HomepageSection = "work" | "building" | "lab" | "game-lab" | "bridge" | "stack-house"
export type MediaKind = "browser-capture" | "ui-preview" | "mobile-preview" | "wireframe" | "concept-art" | "prototype-video" | "game-still" | "architecture" | "worldbuilding" | "model"
export type MediaProvenance = "real" | "concept" | "prototype" | "placeholder"
export type MediaReadiness = "ready" | "pending" | "held"
export interface ProjectMedia { kind:MediaKind; provenance:MediaProvenance; readiness:MediaReadiness; label:string; alt:string; src?:string; note?:string; aspect?:"16:10"|"16:9"|"4:3"|"portrait"|"square" }
export interface ProjectLinks { live?:string; preview?:string; repo?:string; internal?:string }
export interface PortfolioProject {
  id:string; slug:string; name:string; category:ProjectCategory; status:ProjectStatus
  homepage?:{section:HomepageSection;order:number;featured?:boolean}
  hook:string; description:string; role?:string; links:ProjectLinks; tech:string[]
  caseStudy:"available"|"planned"|"none"; houseEligible:boolean; held?:boolean; archived?:boolean
  media:ProjectMedia[]; supporting?:ReadonlyArray<{name:string;label:string}>
}
const capture=(src:string,alt:string):ProjectMedia=>({kind:"browser-capture",provenance:"real",readiness:"ready",label:"LIVE SITE CAPTURE",alt,src,aspect:"16:10"})
const mobileCapture=(src:string,alt:string):ProjectMedia=>({kind:"mobile-preview",provenance:"real",readiness:"ready",label:"LIVE MOBILE CAPTURE",alt,src,aspect:"portrait"})
const labPreview=(src:string,alt:string,provenance:"prototype"|"concept"):ProjectMedia=>({kind:"ui-preview",provenance,readiness:"ready",label:provenance==="concept"?"CONCEPT INTERFACE":"PROTOTYPE CAPTURE",alt,src,aspect:"16:10"})
const gameConcept=(src:string,alt:string):ProjectMedia=>({kind:"game-still",provenance:"concept",readiness:"ready",label:"CONCEPT ART",alt,src,aspect:"16:9"})
const pending=(kind:MediaKind,label:string,alt:string,aspect:ProjectMedia["aspect"]="16:9",note?:string):ProjectMedia=>({kind,provenance:"placeholder",readiness:"pending",label,alt,aspect,note})
const p=(project:PortfolioProject)=>project

export const PORTFOLIO_PROJECTS: PortfolioProject[] = [
 p({id:"grey-key",slug:"grey-key-studios",name:"Grey Key Studios",category:"studio",status:"live",homepage:{section:"work",order:1,featured:true},hook:"One studio. Many identities. No single lane.",description:"The creative home for Michael Walton’s music, artist personas, visual experiments, and independently built technology.",role:"Founder · Creative Director",links:{live:"https://www.greykeystudios.com/"},tech:[],caseStudy:"planned",houseEligible:true,media:[capture("/portfolio/grey-key-studios.png","Grey Key Studios live website")]}),
 p({id:"sbm",slug:"sbm-inc",name:"SBM Inc.",category:"client-work",status:"live",homepage:{section:"work",order:2},hook:"A clearer front door for a community-centered mission.",description:"A welcoming organizational website that brings SBM’s work for BIPOC youth, its mission, and its public presence into one credible place.",role:"Strategy · Design · Build",links:{live:"https://sbminc.org/"},tech:[],caseStudy:"planned",houseEligible:true,media:[capture("/portfolio/sbm-inc.png","SBM Inc. live website")]}),
 p({id:"zachardee",slug:"zachardee-holdings",name:"Zachardee Holdings",category:"client-work",status:"live",homepage:{section:"work",order:3},hook:"Profit with purpose. Integrity with impact.",description:"A polished public home for a holding company that wants its values and long-term purpose to be as visible as its business interests.",links:{live:"https://www.zachardeeholdings.com/"},tech:[],caseStudy:"planned",houseEligible:true,media:[capture("/portfolio/zachardee-holdings.png","Zachardee Holdings live website")]}),
 p({id:"being-black-it",slug:"being-black-in-it",name:"Being Black In IT",category:"community",status:"live",homepage:{section:"work",order:4},hook:"The guidance you wish someone had given you earlier.",description:"Practical career guides, shared knowledge, and grounded resources for Black professionals finding their way through the technology industry.",links:{live:"https://beingblackinit.com/"},tech:[],caseStudy:"planned",houseEligible:true,media:[capture("/portfolio/being-black-in-it.png","Being Black In IT live website")]}),
 p({id:"cloud-resume",slug:"cloud-resume",name:"Cloud Resume",category:"cloud",status:"live",homepage:{section:"work",order:5},hook:"The résumé is only the surface. The infrastructure is the proof.",description:"A working résumé site that turns the cloud architecture behind it into part of the portfolio—not just somewhere to host a PDF.",role:"Cloud Architect · Developer",links:{live:"https://resume.greykeystudios.dev/"},tech:[],caseStudy:"planned",houseEligible:true,media:[capture("/portfolio/cloud-resume.png","Cloud Resume live website")]}),
 p({id:"soc-os",slug:"soc-os",name:"SOC OS",category:"security-portfolio",status:"live",homepage:{section:"work",order:6},hook:"Security+ was the milestone. This was the proof of what came with it.",description:"A cybersecurity portfolio built after earning Security+, bringing security concepts, labs, and technical work into a more deliberate visual presentation.",links:{live:"https://soc.greykeystudios.dev/"},tech:[],caseStudy:"planned",houseEligible:true,media:[capture("/portfolio/soc-os.png","SOC live website")]}),
 p({id:"me-to-we",slug:"me-to-we",name:"Me To We",category:"community",status:"concept",hook:"Held from public display.",description:"Project record retained without publishing unfinished or unapproved material.",links:{},tech:[],caseStudy:"none",houseEligible:false,held:true,media:[{...pending("concept-art","PROJECT HELD","Me To We held project media","4:3"),readiness:"held"}]}),

 p({id:"lifeos",slug:"lifeos",name:"LifeOS",category:"personal-system",status:"vertical-slice",homepage:{section:"building",order:1,featured:true},hook:"A place to run your life—not just make another list.",description:"A personal operating system that brings the moving parts of everyday life into one connected desktop and mobile experience.",links:{live:"https://life-os.greykeystudios.workers.dev/"},tech:[],caseStudy:"planned",houseEligible:true,media:[capture("/portfolio/lifeos.png","LifeOS live application"),mobileCapture("/portfolio/lifeos-mobile.png","LifeOS mobile interface")]}),
 p({id:"careeros",slug:"careeros",name:"CareerOS",category:"career",status:"in-development",homepage:{section:"building",order:2},hook:"Treat the career like a system, not a scramble.",description:"A career-planning workspace for connecting experience, skills, opportunities, and next steps without losing the larger direction.",links:{live:"https://career-os.greykeystudios.workers.dev/"},tech:[],caseStudy:"planned",houseEligible:true,media:[capture("/portfolio/careeros.png","CareerOS live application"),mobileCapture("/portfolio/careeros-mobile.png","CareerOS mobile interface")]}),
 p({id:"diaspora-atlas",slug:"diaspora-atlas",name:"Diaspora Atlas",category:"culture",status:"in-development",homepage:{section:"building",order:3},hook:"Follow the people, places, and stories that maps usually flatten.",description:"An evolving cultural atlas for exploring the movement, memory, and connections of the African diaspora across geography and time.",links:{live:"https://diaspora-atlas-app.greykeystudios.workers.dev/"},tech:[],caseStudy:"planned",houseEligible:true,media:[capture("/portfolio/diaspora-atlas.png","Diaspora Atlas live homepage"),mobileCapture("/portfolio/diaspora-atlas-mobile.png","Diaspora Atlas mobile homepage")]}),
 p({id:"relearn",slug:"relearn",name:"ReLearn",category:"learning",status:"in-development",homepage:{section:"building",order:4},hook:"Return to what you learned. Find out what stayed.",description:"A learning system built around lessons, practice, quizzes, and hands-on activities—beginning with networking and growing into the learning engine behind Bridge Academy.",links:{live:"https://rltest.greykeystudios.dev/"},tech:[],caseStudy:"planned",houseEligible:true,media:[capture("/portfolio/relearn.png","ReLearn live application"),mobileCapture("/portfolio/relearn-mobile.png","ReLearn mobile interface")]}),
 p({id:"gk-plugin-suite",slug:"gk-plugin-suite",name:"GK Plugin Suite + GK Studio DAW",category:"creative-tool",status:"in-development",homepage:{section:"building",order:5},hook:"Build the instruments. Shape the sound. Keep it in the same world.",description:"A growing family of Grey Key music tools, from individual audio plugins to a larger studio environment for producing, experimenting, and developing new sounds.",links:{live:"https://gks5.greykeystudios.workers.dev/"},tech:[],caseStudy:"planned",houseEligible:true,media:[capture("/portfolio/gk-plugin-suite.png","GK Plugin Suite live preview website"),mobileCapture("/portfolio/gk-plugin-suite-mobile.png","GK Plugin Suite mobile website")]}),
 p({id:"voiceover-lab",slug:"voiceover-lab",name:"Voiceover Lab",category:"creative-tool",status:"vertical-slice",homepage:{section:"building",order:6},hook:"A private rehearsal room for finding the performance.",description:"A local-first practice studio where aspiring voice actors can choose a script, record a take, listen back, review the performance, and try again.",role:"Creator · Product Direction · AI-assisted Development",links:{live:"https://voiceoverlab.greykeystudios.workers.dev/",repo:"https://github.com/GreyKeyStudios/voiceoverlab"},tech:["Next.js","MediaRecorder","IndexedDB"],caseStudy:"planned",houseEligible:true,media:[capture("/portfolio/voiceover-lab.png","VOICE//ROOM guest web Practice dashboard"),mobileCapture("/portfolio/voiceover-lab-mobile.png","VOICE//ROOM mobile dashboard")]}),
 p({id:"baseka",slug:"baseka",name:"Baseka",category:"personal-finance",status:"scaffold",homepage:{section:"building",order:7},hook:"Know what your money can safely do next.",description:"An early personal-finance system for understanding cash flow, expenses, obligations, reserves, and what remains available after the important promises are protected.",links:{live:"https://baseka.greykeystudios.workers.dev/"},tech:[],caseStudy:"planned",houseEligible:true,media:[capture("/portfolio/baseka.png","Baseka live application"),mobileCapture("/portfolio/baseka-mobile.png","Baseka mobile interface")]}),
 p({id:"ahoden",slug:"ahoden-name-pending",name:"Ahoden — Name Pending",category:"health",status:"scaffold",homepage:{section:"building",order:8},hook:"What can your body support today?",description:"An early health-and-fitness system designed around recovery, sustainable progress, and choosing the smallest useful action that keeps you moving forward.",links:{live:"https://ahoden.greykeystudios.workers.dev/"},tech:[],caseStudy:"none",houseEligible:false,media:[capture("/portfolio/ahoden.png","Ahoden live application"),mobileCapture("/portfolio/ahoden-mobile.png","Ahoden mobile interface")]}),
 p({id:"suuru",slug:"suuru",name:"Suuru",category:"trading-literacy",status:"scaffold",homepage:{section:"building",order:9},hook:"Prove the trade before you place it.",description:"An evidence-first trading education system for learning how markets work, building a testable thesis, practicing with simulated capital, managing risk, and reviewing the outcome before considering live trading.",links:{live:"https://suuru.greykeystudios.workers.dev/"},tech:[],caseStudy:"none",houseEligible:true,media:[capture("/portfolio/suuru.png","Suuru live application"),mobileCapture("/portfolio/suuru-mobile.png","Suuru mobile interface")]}),

 p({id:"app-triage",slug:"app-triage",name:"App Triage",category:"support-tool",status:"in-development",homepage:{section:"lab",order:1},hook:"Keep the call moving without losing the person—or the problem.",description:"A focused support workflow that guides an agent through one decision at a time, keeps the next useful action visible, and turns the call into organized handoff notes.",links:{live:"https://at-test.greykeystudios.workers.dev/"},tech:["Next.js","TypeScript"],caseStudy:"planned",houseEligible:true,media:[{kind:"ui-preview",provenance:"real",readiness:"ready",label:"LIVE APP CAPTURE",alt:"App Triage guided support workflow and generated handoff notes",src:"/portfolio/app-triage.png",aspect:"16:10"}]}),
 p({id:"citizen-science",slug:"citizen-science",name:"Citizen Science",category:"research",status:"concept",homepage:{section:"lab",order:2},hook:"What could we learn if everyday observations had somewhere to go?",description:"A proposed research workspace where people can document what they notice, contribute evidence, and help turn scattered observations into shared knowledge.",links:{},tech:[],caseStudy:"none",houseEligible:false,media:[labPreview("/portfolio/citizen-science.png","Citizen Science concept interface","concept")]}),
 p({id:"chart-colleseum",slug:"chart-colleseum",name:"Chart Coliseum",category:"research",status:"prototype",homepage:{section:"lab",order:3},hook:"Bring a claim. Enter the arena. Defend it with data.",description:"A competitive data experience that turns charts, evidence, and interpretation into something closer to a match than a lecture.",links:{},tech:[],caseStudy:"none",houseEligible:false,media:[labPreview("/portfolio/chart-colosseum.png","Chart Coliseum arena splash screen","prototype")]}),
 p({id:"deal-radar",slug:"deal-radar",name:"Deal Radar",category:"research",status:"scaffold",homepage:{section:"lab",order:4},hook:"Find the signal before the opportunity becomes obvious.",description:"A deal-discovery system exploring how public data, property information, market conditions, and acquisition criteria can surface opportunities worth investigating.",links:{},tech:[],caseStudy:"none",houseEligible:false,media:[labPreview("/portfolio/deal-radar.png","Deal Radar dashboard preview","prototype")]}),
 p({id:"crossword-builder",slug:"crossword-builder",name:"Crossword Builder",category:"research",status:"prototype",homepage:{section:"lab",order:5},hook:"A construction desk for people who think in clues.",description:"A workspace for building, refining, testing, and sharing crossword puzzles without losing sight of either the grid or the solver’s experience.",links:{},tech:[],caseStudy:"none",houseEligible:false,media:[labPreview("/portfolio/crossword-builder.png","Crossword Builder workspace preview","prototype")]}),
 p({id:"opportunity-fit",slug:"opportunity-fit",name:"Opportunity Fit",category:"research",status:"prototype",homepage:{section:"lab",order:6},hook:"Not every opportunity fits the work. Find the ones that do.",description:"A matching workspace that compares active projects, credentials, and readiness against grants, scholarships, accelerators, and other opportunities.",links:{},tech:[],caseStudy:"none",houseEligible:false,media:[labPreview("/portfolio/opportunity-fit.png","Opportunity Fit dashboard preview","prototype")]}),

 ...([
  {id:"cooleys-revenge",slug:"cooleys-revenge",name:"Cooley’s Revenge",hook:"The Man built the system. Cooley brought the fight to it.",description:"A Blaxploitation-era fighting game shaped by larger-than-life heroes, villains, rivalries, style, music, and the political charge of the films that inspired it.",src:"/portfolio/cooleys-revenge.webp"},
  {id:"molt",slug:"molt",name:"MOLT",hook:"Survival gets you through the day. Evolution decides what comes next.",description:"A large-scale animal survival MMO where species compete, adapt, migrate, and evolve inside an ecosystem reshaped by predators, biomes, scarcity, and catastrophic events.",src:"/portfolio/molt.webp"},
  {id:"pilot-city",slug:"pilot-city",name:"Pilot City",hook:"Fight your way down West Broadway. Try not to fall beneath it.",description:"A beat-’em-up set in an exaggerated city inspired by West Broadway—loud and familiar on the surface, with something far stranger living underneath.",src:"/portfolio/pilot-city.webp"},
  {id:"youre-it",slug:"youre-it",name:"You’re It",hook:"Someone is always it. The problem is finding out who.",description:"A stealth-horror puzzle game built around pursuit, hiding, observation, and the uneasy rules of a childhood game that has become something else.",src:"/portfolio/youre-it.webp"},
  {id:"floor-is-negotiable",slug:"the-floor-is-negotiable",name:"The Floor Is Negotiable",hook:"The floor is not lava. That would be easier.",description:"A precision puzzle-and-rage game where the ground, the rules, and sometimes the meaning of progress refuse to stay settled.",src:"/portfolio/floor-is-negotiable.webp"},
  {id:"corporate-espionage-sim",slug:"corporate-espionage-sim",name:"Corporate Espionage Sim",hook:"Break into the company. Break apart the system. Learn how it was secured.",description:"An action RPG and corporate-infiltration simulator that turns cybersecurity concepts into missions involving reconnaissance, access, social engineering, defense, and consequence.",src:"/portfolio/corporate-espionage-sim.webp"},
  {id:"life-horror-game",slug:"life-horror-game",name:"Life: A Horror Game",hook:"No monster. No jumpscares. Just everything waiting for you.",description:"A side-on RPG horror game about surviving ordinary life when money, work, maintenance, relationships, and time keep closing in at once.",src:"/portfolio/life-horror-game.webp"},
  {id:"kids-at-the-mall",slug:"kids-at-the-mall",name:"Kids at the Mall: ’97 Edition",hook:"The mall is closing. The night is just getting started.",description:"A multiplayer stealth-adventure party game about kids navigating a late-’90s mall after hours—sneaking past adults, chasing objectives, causing trouble, and trying not to get caught.",src:"/portfolio/kids-at-the-mall.webp"},
 ] as const).map((game,index)=>p({id:game.id,slug:game.slug,name:game.name,category:"game",status:"concept",homepage:{section:"game-lab",order:index+1,featured:index===0},hook:game.hook,description:game.description,links:{},tech:[],caseStudy:"planned",houseEligible:true,media:[gameConcept(game.src,`${game.name} concept art`)]})),
 p({id:"grey-key-arcade",slug:"grey-key-arcade",name:"Grey Key Arcade",category:"gaming-system",status:"vertical-slice",homepage:{section:"game-lab",order:9},hook:"One library. Every era. Pick up the controller.",description:"A controller-first living-room launcher that brings emulated and native games into one library, follows a removable collection across drives, starts verified backends, and returns the player to the same ten-foot interface when a session ends.",role:"Creator · Product Direction · Development",links:{repo:"https://github.com/GreyKeyStudios/gk-emulator"},tech:["Node.js","SQLite","RetroArch","PPSSPP","Dolphin"],caseStudy:"planned",houseEligible:true,media:[{kind:"ui-preview",provenance:"real",readiness:"ready",label:"LOCAL APP CAPTURE",alt:"Grey Key Arcade console browser on the local launcher",src:"/portfolio/grey-key-arcade.png",aspect:"16:9"}]}),
 p({id:"gk-backlot",slug:"gk-backlot",name:"GK Backlot",category:"worldbuilding",status:"prototype",homepage:{section:"game-lab",order:10},hook:"Build the place once. Let many stories move through it.",description:"A reusable environment system for Grey Key games, combining developed locations, modular building pieces, greybox sites, and reserved spaces that can grow with future stories.",links:{},tech:[],caseStudy:"planned",houseEligible:true,media:[gameConcept("/portfolio/gk-backlot.webp","GK Backlot modular city concept art")],supporting:[{name:"Motel",label:"ENVIRONMENT SLOT"},{name:"Self-storage facility",label:"ENVIRONMENT SLOT"},{name:"Apartment",label:"ENVIRONMENT SLOT"},{name:"Radio station",label:"ENVIRONMENT SLOT"}]}),

 p({id:"bridge-academy",slug:"bridge-academy",name:"Bridge Academy",category:"education",status:"concept",homepage:{section:"bridge",order:1,featured:true},hook:"Build better builders.",description:"A proposed digital-first school system where students learn by investigating real questions, building working projects, troubleshooting what fails, and demonstrating what they know across technology, music, culture, and applied STEM.",links:{},tech:[],caseStudy:"planned",houseEligible:true,media:[{kind:"concept-art",provenance:"concept",readiness:"ready",label:"PLANNING WORKBENCH",alt:"Bridge Academy planning workbench with curriculum, music hardware, computing, electronics, historical material, and diagrams",src:"/portfolio/bridge-academy-hero.webp",aspect:"16:10"}]}),
 p({id:"stack-house",slug:"stack-house",name:"The Stack House",category:"interactive",status:"in-development",homepage:{section:"stack-house",order:1,featured:true},hook:"The portfolio has another door.",description:"A walkable house where projects live inside rooms, devices, studios, and hidden spaces—part portfolio, part story, and part world still being built.",links:{internal:"/house"},tech:[],caseStudy:"planned",houseEligible:true,media:[{kind:"model",provenance:"real",readiness:"ready",label:"INTERACTIVE HOUSE MODEL",alt:"The Stack House interactive 3D model",src:"/models/house-main-optimized.glb",aspect:"16:9"}]}),
]

export const projectsFor=(section:HomepageSection)=>PORTFOLIO_PROJECTS.filter(x=>!x.held&&!x.archived&&x.homepage?.section===section).sort((a,b)=>(a.homepage!.order-b.homepage!.order))
export const SHIPPED_PROJECTS=projectsFor("work"), BUILDING_PROJECTS=projectsFor("building"), LAB_PROJECTS=projectsFor("lab"), GAME_PROJECTS=projectsFor("game-lab")
export const BRIDGE_PROJECT=projectsFor("bridge")[0], STACK_HOUSE_PROJECT=projectsFor("stack-house")[0]

export type IdentityTransition = "shutter" | "prism" | "film-burn" | "scanline" | "double-exposure" | "ink" | "signal"
export type IdentityAsset = { src?:string; alt:string; placeholder:string }
export interface MusicPreview {
  id:string; title:string; projectId?:string; audioSrc:string; artwork?:IdentityAsset
  sourceRef?:string; startSeconds?:number; endSeconds?:number
}
export interface MusicProject { id:string;title:string;artwork?:IdentityAsset;trackCandidates:string[];note?:string }
export interface MusicIdentity {
  id:string;name:string;descriptor:string;blurb:string;transition:IdentityTransition;basePortrait:IdentityAsset
  personaPortrait:IdentityAsset;logoFallback:IdentityAsset;artwork:IdentityAsset;audioLabel:string
  credits:string;projects:MusicProject[];previews:MusicPreview[];status:"identity-study"|"archive-ready";aside?:string
}
const baseMichael:IdentityAsset={src:"/portfolio/music/artists/michael-walton.png",alt:"Michael Walton portrait",placeholder:"BASE PORTRAIT / MICHAEL WALTON"}
const artist=(src:string,alt:string,placeholder:string):IdentityAsset=>({src,alt,placeholder})
const projectArt=(src:string,alt:string,placeholder:string):IdentityAsset=>({src,alt,placeholder})
export const MUSIC_IDENTITIES:MusicIdentity[]=[
 {id:"mr-e",name:"Mr. E",descriptor:"Cinematic hip-hop · retro games · science fiction",blurb:"Story records, strange transmissions, public-domain fragments, and music that sounds like it escaped from a game or film that never existed.",transition:"shutter",basePortrait:baseMichael,personaPortrait:artist("/portfolio/music/artists/mr-e.webp","Mr. E persona portrait","MR. E / PERSONA PORTRAIT"),logoFallback:artist("/portfolio/music/artists/mr-e.webp","Mr. E identity artwork","MR. E / IDENTITY"),artwork:projectArt("/portfolio/music/projects/destination-terra-gaia.webp","Destination: Terra Gaia project artwork","DESTINATION: TERRA GAIA / PROJECT ARTWORK"),audioLabel:"Mr. E preview queue",credits:"Michael Walton · identity and music",projects:[
  {id:"builders-of-the-future",title:"Builders of the Future",trackCandidates:[],note:"Artwork and music selection TBD"},
  {id:"destination-terra-gaia",title:"Destination: Terra Gaia",artwork:projectArt("/portfolio/music/projects/destination-terra-gaia.webp","Destination: Terra Gaia project artwork","DESTINATION: TERRA GAIA / PROJECT ARTWORK"),trackCandidates:["Lilas Lusty Lore","Starry Sojourn","Secure Comms"]},
  {id:"games-on-channel-3",title:"Games on Channel 3",artwork:projectArt("/portfolio/music/projects/games-on-channel-3.webp","Games on Channel 3 project artwork","GAMES ON CHANNEL 3 / PROJECT ARTWORK"),trackCandidates:[],note:"Two-song project; preview selection TBD"},
 ],previews:[],status:"identity-study"},
 {id:"beautiful-uglies",name:"The Beautiful Uglies",descriptor:"Neo-soul · psychedelic · experimental",blurb:"The original Grey Key band: raw, genre-blending, emotionally uneven on purpose, and always capable of changing shape if the right musicians enter the room.",transition:"prism",basePortrait:baseMichael,personaPortrait:artist("/portfolio/music/artists/the-beautiful-uglies.webp","The Beautiful Uglies group portrait","THE BEAUTIFUL UGLIES / GROUP PORTRAIT"),logoFallback:artist("/portfolio/music/artists/the-beautiful-uglies.webp","The Beautiful Uglies identity artwork","THE BEAUTIFUL UGLIES / IDENTITY"),artwork:projectArt("/portfolio/music/projects/soundtrack-for-an-unmade-film.jpg","Soundtrack for an Unmade Film project artwork","SOUNDTRACK FOR AN UNMADE FILM / PROJECT ARTWORK"),audioLabel:"The Beautiful Uglies preview queue",credits:"Michael Walton · creative direction",projects:[
  {id:"soundtrack-for-an-unmade-film",title:"Soundtrack for an Unmade Film",artwork:projectArt("/portfolio/music/projects/soundtrack-for-an-unmade-film.jpg","Soundtrack for an Unmade Film project artwork","SOUNDTRACK FOR AN UNMADE FILM / PROJECT ARTWORK"),trackCandidates:[]},
  {id:"midnight-blues",title:"Midnight Blues",trackCandidates:["Midnight Blues 2","Midnight Blues","Tacit 2"],note:"Two additional selections and final artwork TBD"},
  {id:"a-series-of-failures",title:"A Series of Failures",artwork:projectArt("/portfolio/music/projects/a-series-of-failures.jpg","A Series of Failures project artwork","A SERIES OF FAILURES / PROJECT ARTWORK"),trackCandidates:["Toy 2"],note:"Additional selections TBD"},
  {id:"liminal-spaces",title:"Liminal Spaces (working title: 1317)",trackCandidates:["Abysmal","Space Race","Mango Mobile","Buffalo Roam"],note:"A house fire, temporary homes, and the places between them retold through a liminal world; final title and artwork still in development"},
 ],previews:[],status:"identity-study"},
 {id:"adwo-nyumbani",name:"Adwo Nyumbani",descriptor:"Jazz · fusion · meditation · homecoming",blurb:"The jazz side of Grey Key: calm without becoming background music, shaped by fusion, breakbeats, memory, and the attempt to make music built inside a computer feel played rather than placed.",transition:"film-burn",basePortrait:baseMichael,personaPortrait:artist("/portfolio/music/artists/adwo-nyumbani.webp","Adwo Nyumbani persona portrait","ADWO NYUMBANI / PERSONA PORTRAIT"),logoFallback:artist("/portfolio/music/artists/adwo-nyumbani.webp","Adwo Nyumbani identity artwork","ADWO NYUMBANI / IDENTITY"),artwork:projectArt("/portfolio/music/projects/calm-home.jpg","Calm Home project artwork","CALM HOME / PROJECT ARTWORK"),audioLabel:"Adwo Nyumbani preview queue",credits:"Michael Walton · identity and music",projects:[
  {id:"calm-home",title:"Calm Home",artwork:projectArt("/portfolio/music/projects/calm-home.jpg","Calm Home project artwork","CALM HOME / PROJECT ARTWORK"),trackCandidates:[]},
  {id:"a-lamenting-waltz",title:"A Lamenting Waltz in C# Minor",trackCandidates:[],note:"Source music and artwork still need to be located"},
  {id:"1899-waltz",title:"1899 Waltz (feat. Mr. E)",artwork:projectArt("/portfolio/music/projects/1899-waltz.webp","1899 Waltz single artwork","1899 WALTZ / SINGLE ARTWORK"),trackCandidates:["1899 Waltz"],note:"Released single featuring Mr. E; also appears on the album Abstract Waltz"},
  {id:"abstract-waltz",title:"Abstract Waltz",artwork:projectArt("/portfolio/music/projects/abstract-waltz.webp","Abstract Waltz project artwork","ABSTRACT WALTZ / PROJECT ARTWORK"),trackCandidates:["1899 Waltz"],note:"Album; includes the single 1899 Waltz (feat. Mr. E)"},
  {id:"the-golden-stool",title:"The Golden Stool",artwork:projectArt("/portfolio/music/projects/the-golden-stool.jpg","The Golden Stool project artwork","THE GOLDEN STOOL / PROJECT ARTWORK"),trackCandidates:["Homecoming"]},
 ],previews:[],status:"identity-study",aside:"Yes, this is still Michael. Jazz needed its own room."},
 {id:"walton-grey",name:"Walton Grey",descriptor:"Post-rock · bedroom pop · jazz-shaped indie",blurb:"The outlet for guitars, soft-focus electronics, awkward vocals, and songs that pull from post-rock, bedroom pop, jazz, soul, and whatever else refuses to stay in one genre.",transition:"scanline",basePortrait:baseMichael,personaPortrait:artist("/portfolio/music/artists/walton-grey.webp","Walton Grey persona portrait","WALTON GREY / PERSONA PORTRAIT"),logoFallback:artist("/portfolio/music/artists/walton-grey.webp","Walton Grey identity artwork","WALTON GREY / IDENTITY"),artwork:projectArt("/portfolio/music/projects/private-karate.jpg","Private Karate project artwork","PRIVATE KARATE / PROJECT ARTWORK"),audioLabel:"Walton Grey preview queue",credits:"Michael Walton · identity and music",projects:[
  {id:"private-karate",title:"Private Karate",artwork:projectArt("/portfolio/music/projects/private-karate.jpg","Private Karate project artwork","PRIVATE KARATE / PROJECT ARTWORK"),trackCandidates:["OCB","Private Karate","Loungewear","Health","Mitchy Pitch","Hap Ness Monsta"]},
  {id:"plastic-horizons",title:"Plastic Horizons",artwork:projectArt("/portfolio/music/projects/plastic-horizons.webp","Plastic Horizons project artwork","PLASTIC HORIZONS / PROJECT ARTWORK"),trackCandidates:["Jumpin Jack Flash","Sudsy OG","Forrest Spitaker"]},
  {id:"cardboard-portraits",title:"Cardboard Portraits",artwork:projectArt("/portfolio/music/projects/cardboard-portraits.webp","Cardboard Portraits project artwork","CARDBOARD PORTRAITS / PROJECT ARTWORK"),trackCandidates:["Ive Come To Come","Smack Dab On The Eighth","My Stuff"]},
  {id:"lighthouse",title:"Lighthouse",trackCandidates:["Sunshine and Mangoes","False Nostalgia","Going Retro","King Of The Hill","Sweet Fading Mattress"],note:"Final artwork still required"},
 ],previews:[],status:"identity-study"},
 {id:"mic-titan",name:"Mic Titan",descriptor:"Hip-hop instrumentals · remixes · sample flips",blurb:"Michael’s first producer name, retired during a long break from music and now reopened for the beats, remixes, and sample-driven work that started everything.",transition:"double-exposure",basePortrait:baseMichael,personaPortrait:artist("/portfolio/music/artists/mic-titan.webp","Mic Titan persona portrait","MIC TITAN / PERSONA PORTRAIT"),logoFallback:artist("/portfolio/music/artists/mic-titan.webp","Mic Titan identity artwork","MIC TITAN / IDENTITY"),artwork:artist("/portfolio/music/artists/mic-titan.webp","Mic Titan identity artwork","MIC TITAN / PROJECT ARTWORK"),audioLabel:"Mic Titan preview queue",credits:"Michael Walton · identity and music",projects:[
  {id:"remix-projects",title:"Three remix projects",trackCandidates:[],note:"Approximately 2–4 representative remixes to be selected"},
  {id:"unreleased-collections",title:"Older unreleased collections",trackCandidates:[],note:"Approximately 2–3 collections and six representative beats to be selected"},
 ],previews:[],status:"identity-study",aside:"The name came first. The archive came later. The return is still in progress."},
 {id:"chno",name:"CHNO",descriptor:"Generative music · disclosed collaboration",blurb:"A clearly labeled home for music in which generative AI materially participates in writing, production, transformation, or performance.",transition:"signal",basePortrait:baseMichael,personaPortrait:artist("/portfolio/music/artists/chno.webp","CHNO persona portrait","CHNO / PERSONA PORTRAIT"),logoFallback:artist("/portfolio/music/artists/chno.webp","CHNO identity artwork","CHNO / IDENTITY"),artwork:artist("/portfolio/music/artists/chno.webp","CHNO identity artwork","CHNO / PROJECT ARTWORK"),audioLabel:"CHNO preview queue",credits:"Michael Walton · generative music identity",projects:[],previews:[],status:"identity-study",aside:"CHNO does not disguise how the music was made. The involvement of generative systems is part of the identity, not fine print added afterward."},
]
export const resolveMusicPreviewArtwork=(identity:MusicIdentity,preview:MusicPreview):IdentityAsset=>preview.artwork??identity.projects.find(project=>project.id===preview.projectId)?.artwork??identity.logoFallback
export const MUSIC_CREDITS=[
 {name:"Uncle Fart",descriptor:"Filthy, anything-goes music"},
 {name:"The Bobby Backfat Band",descriptor:"Jazz-funk · fusion · deep-pocket grooves"},
 {name:"Lemon Ice",descriptor:"Trap parody · wrong subjects, right drums"},
 {name:"Samon",descriptor:"Metal · no missing L required"},
 {name:"Uncle Arctica",descriptor:"Electronic collaboration · final configuration open"},
 {name:"The Broken Shortcuts",descriptor:"Covers, rebuilt the Grey Key way"},
 {name:"Night Movers",descriptor:"Nocturnal soft psych · bedroom pop · slow glow"},
 {name:"Kief Swette",descriptor:"Raunchy R&B crooner"},
].map(({name,descriptor},index)=>({id:`credit-${index}`,name,descriptor,artwork:{alt:`${name} identity artwork`,placeholder:`${name.toUpperCase()} / IDENTITY ART`} as IdentityAsset}))
