export type ProjectStatus = "live" | "vertical-slice" | "in-development" | "prototype" | "scaffold" | "concept"
export const STATUS_LABELS: Record<ProjectStatus,string> = { live:"Live", "vertical-slice":"Vertical Slice", "in-development":"In Development", prototype:"Prototype", scaffold:"Scaffold", concept:"Concept" }
export type ProjectCategory = "studio" | "client-work" | "community" | "cloud" | "security" | "personal-system" | "career" | "culture" | "learning" | "creative-tool" | "platform" | "research" | "game" | "worldbuilding" | "education" | "interactive"
export const CATEGORY_LABELS: Record<ProjectCategory,string> = { studio:"Creative Studio", "client-work":"Client Work", community:"Community", cloud:"Cloud Engineering", security:"Security Operations", "personal-system":"Personal Systems", career:"Career Tools", culture:"Culture", learning:"Learning", "creative-tool":"Creative Tools", platform:"Platform", research:"Research Lab", game:"Game", worldbuilding:"Worldbuilding", education:"Education", interactive:"Interactive Experience" }
export type HomepageSection = "work" | "building" | "lab" | "game-lab" | "bridge" | "stack-house"
export type MediaKind = "browser-capture" | "ui-preview" | "mobile-preview" | "wireframe" | "concept-art" | "prototype-video" | "game-still" | "architecture" | "worldbuilding" | "model"
export type MediaProvenance = "real" | "concept" | "prototype" | "placeholder"
export type MediaReadiness = "ready" | "pending" | "held"
export interface ProjectMedia { kind:MediaKind; provenance:MediaProvenance; readiness:MediaReadiness; label:string; alt:string; src?:string; note?:string; aspect?:"16:10"|"16:9"|"4:3"|"portrait"|"square" }
export interface ProjectLinks { live?:string; preview?:string; repo?:string; internal?:string }
export interface PortfolioProject {
  id:string; slug:string; name:string; category:ProjectCategory; status:ProjectStatus
  homepage?:{section:HomepageSection;order:number;featured?:boolean}
  hook:string; description:string; role?:string; links:ProjectLinks; tech:string[]
  caseStudy:"available"|"planned"|"none"; houseEligible:boolean; held?:boolean; archived?:boolean
  media:ProjectMedia[]; supporting?:ReadonlyArray<{name:string;label:string}>
}
const capture=(src:string,alt:string):ProjectMedia=>({kind:"browser-capture",provenance:"real",readiness:"ready",label:"LIVE SITE CAPTURE",alt,src,aspect:"16:10"})
const mobileCapture=(src:string,alt:string):ProjectMedia=>({kind:"mobile-preview",provenance:"real",readiness:"ready",label:"LIVE MOBILE CAPTURE",alt,src,aspect:"portrait"})
const gameConcept=(src:string,alt:string):ProjectMedia=>({kind:"game-still",provenance:"concept",readiness:"ready",label:"CONCEPT ART",alt,src,aspect:"16:9"})
const pending=(kind:MediaKind,label:string,alt:string,aspect:ProjectMedia["aspect"]="16:9",note?:string):ProjectMedia=>({kind,provenance:"placeholder",readiness:"pending",label,alt,aspect,note})
const p=(project:PortfolioProject)=>project

export const PORTFOLIO_PROJECTS: PortfolioProject[] = [
 p({id:"grey-key",slug:"grey-key-studios",name:"Grey Key Studios",category:"studio",status:"live",homepage:{section:"work",order:1,featured:true},hook:"Independent culture, built under one roof.",description:"A home for music, identity, experiments, and creative technology.",role:"Founder · Creative Director",links:{live:"https://www.greykeystudios.com/"},tech:[],caseStudy:"planned",houseEligible:true,media:[capture("/portfolio/grey-key-studios.png","Grey Key Studios live website")]}),
 p({id:"sbm",slug:"sbm-inc",name:"SBM Inc.",category:"client-work",status:"live",homepage:{section:"work",order:2},hook:"A credible digital front door for a community organization.",description:"A client-facing presence for an organization empowering BIPOC youth.",role:"Strategy · Design · Build",links:{live:"https://sbminc.org/"},tech:[],caseStudy:"planned",houseEligible:true,media:[capture("/portfolio/sbm-inc.png","SBM Inc. live website")]}),
 p({id:"zachardee",slug:"zachardee-holdings",name:"Zachardee Holdings",category:"client-work",status:"live",homepage:{section:"work",order:3},hook:"Profit with purpose. Integrity with impact.",description:"A shipped digital presence for a purpose-driven holding company.",links:{live:"https://www.zachardeeholdings.com/"},tech:[],caseStudy:"planned",houseEligible:true,media:[capture("/portfolio/zachardee-holdings.png","Zachardee Holdings live website")]}),
 p({id:"being-black-it",slug:"being-black-in-it",name:"Being Black In IT",category:"community",status:"live",homepage:{section:"work",order:4},hook:"Practical career guides for Black professionals in tech.",description:"A shipped community-facing guide and resource platform.",links:{live:"https://beingblackinit.com/"},tech:[],caseStudy:"planned",houseEligible:true,media:[capture("/portfolio/being-black-in-it.png","Being Black In IT live website")]}),
 p({id:"cloud-resume",slug:"cloud-resume",name:"Cloud Resume",category:"cloud",status:"live",homepage:{section:"work",order:5},hook:"The infrastructure is part of the story.",description:"A production resume platform built to make cloud engineering visible.",role:"Cloud Architect · Developer",links:{live:"https://resume.greykeystudios.dev/"},tech:[],caseStudy:"planned",houseEligible:true,media:[capture("/portfolio/cloud-resume.png","Cloud Resume live website")]}),
 p({id:"soc-os",slug:"soc-os",name:"SOC OS",category:"security",status:"live",homepage:{section:"work",order:6},hook:"Signal, response, and less operational noise.",description:"A focused operating layer for security work.",role:"Product · Engineering",links:{live:"https://soc.greykeystudios.dev/"},tech:[],caseStudy:"planned",houseEligible:true,media:[capture("/portfolio/soc-os.png","SOC live website")]}),
 p({id:"me-to-we",slug:"me-to-we",name:"Me To We",category:"community",status:"concept",hook:"Held from public display.",description:"Project record retained without publishing unfinished or unapproved material.",links:{},tech:[],caseStudy:"none",houseEligible:false,held:true,media:[{...pending("concept-art","PROJECT HELD","Me To We held project media","4:3"),readiness:"held"}]}),

 p({id:"lifeos",slug:"lifeos",name:"LifeOS",category:"personal-system",status:"vertical-slice",homepage:{section:"building",order:1,featured:true},hook:"A working slice of a personal operating system.",description:"A system in active development; detailed product media is pending.",links:{live:"https://life-os.greykeystudios.workers.dev/"},tech:[],caseStudy:"planned",houseEligible:true,media:[capture("/portfolio/lifeos.png","LifeOS live application"),mobileCapture("/portfolio/lifeos-mobile.png","LifeOS mobile interface")]}),
 p({id:"careeros",slug:"careeros",name:"CareerOS",category:"career",status:"in-development",homepage:{section:"building",order:2},hook:"Career decisions as a system, not a scramble.",description:"An active build with product details reserved for verified preview media.",links:{live:"https://career-os.greykeystudios.workers.dev/"},tech:[],caseStudy:"planned",houseEligible:true,media:[capture("/portfolio/careeros.png","CareerOS live application"),mobileCapture("/portfolio/careeros-mobile.png","CareerOS mobile interface")]}),
 p({id:"diaspora-atlas",slug:"diaspora-atlas",name:"Diaspora Atlas",category:"culture",status:"in-development",homepage:{section:"building",order:3},hook:"A cultural map taking shape.",description:"An active build; imagery and product detail remain intentionally pending.",links:{live:"https://diaspora-atlas-app.greykeystudios.workers.dev/"},tech:[],caseStudy:"planned",houseEligible:true,media:[capture("/portfolio/diaspora-atlas.png","Diaspora Atlas live homepage"),mobileCapture("/portfolio/diaspora-atlas-mobile.png","Diaspora Atlas mobile homepage")]}),
 p({id:"relearn",slug:"relearn",name:"ReLearn",category:"learning",status:"in-development",homepage:{section:"building",order:4},hook:"Return to what you once knew.",description:"An AI-assisted relearning and study-tool project in development.",links:{live:"https://rltest.greykeystudios.dev/"},tech:[],caseStudy:"planned",houseEligible:true,media:[capture("/portfolio/relearn.png","ReLearn live application"),mobileCapture("/portfolio/relearn-mobile.png","ReLearn mobile interface")]}),
 p({id:"gk-plugin-suite",slug:"gk-plugin-suite",name:"GK Plugin Suite + GK Studio DAW",category:"creative-tool",status:"in-development",homepage:{section:"building",order:5},hook:"Tools for making sound inside the Grey Key world.",description:"A live preview home for the Grey Key plugin family, with the GK Studio DAW joining the same experience as it develops.",links:{live:"https://gks5.greykeystudios.workers.dev/"},tech:[],caseStudy:"planned",houseEligible:true,media:[capture("/portfolio/gk-plugin-suite.png","GK Plugin Suite live preview website"),mobileCapture("/portfolio/gk-plugin-suite-mobile.png","GK Plugin Suite mobile website")]}),
 p({id:"voiceover-lab",slug:"voiceover-lab",name:"Voiceover Lab",category:"creative-tool",status:"vertical-slice",homepage:{section:"building",order:6},hook:"A private practice room for finding the performance.",description:"A local-first studio where aspiring voice actors can choose or paste a script, record takes, listen back, review their work, and improve.",role:"Creator · Product Direction · AI-assisted Development",links:{live:"https://voiceoverlab.greykeystudios.workers.dev/",repo:"https://github.com/GreyKeyStudios/voiceoverlab"},tech:["Next.js","MediaRecorder","IndexedDB"],caseStudy:"planned",houseEligible:true,media:[capture("/portfolio/voiceover-lab.png","VOICE//ROOM guest web Practice dashboard"),mobileCapture("/portfolio/voiceover-lab-mobile.png","VOICE//ROOM mobile dashboard")]}),
 p({id:"baseka",slug:"baseka",name:"Baseka",category:"platform",status:"scaffold",homepage:{section:"building",order:7},hook:"Foundation first.",description:"A scaffold-stage project with scope and media intentionally reserved.",links:{live:"https://baseka.greykeystudios.workers.dev/"},tech:[],caseStudy:"planned",houseEligible:true,media:[capture("/portfolio/baseka.png","Baseka live application"),mobileCapture("/portfolio/baseka-mobile.png","Baseka mobile interface")]}),
 p({id:"ahoden",slug:"ahoden-name-pending",name:"Ahoden — Name Pending",category:"platform",status:"scaffold",homepage:{section:"building",order:8},hook:"The project exists before the final name does.",description:"A scaffold-stage project whose public identity is still unresolved.",links:{live:"https://ahoden.greykeystudios.workers.dev/"},tech:[],caseStudy:"none",houseEligible:false,media:[capture("/portfolio/ahoden.png","Ahoden live application"),mobileCapture("/portfolio/ahoden-mobile.png","Ahoden mobile interface")]}),
 p({id:"suuru",slug:"suuru",name:"Suuru",category:"platform",status:"scaffold",homepage:{section:"building",order:9},hook:"An early system establishing its first durable shape.",description:"Scaffold-stage work with no fabricated product preview.",links:{live:"https://suuru.greykeystudios.workers.dev/"},tech:[],caseStudy:"none",houseEligible:true,media:[capture("/portfolio/suuru.png","Suuru live application"),mobileCapture("/portfolio/suuru-mobile.png","Suuru mobile interface")]}),

 p({id:"citizen-science",slug:"citizen-science",name:"Citizen Science",category:"research",status:"concept",homepage:{section:"lab",order:1},hook:"A question looking for an interface.",description:"A participation-driven research workspace for turning everyday observations into collective knowledge.",links:{},tech:[],caseStudy:"none",houseEligible:false,media:[capture("/portfolio/citizen-science.png","Citizen Science research workspace preview")]}),
 p({id:"chart-colleseum",slug:"chart-colleseum",name:"Chart Colleseum",category:"research",status:"prototype",homepage:{section:"lab",order:2},hook:"Data enters the arena.",description:"A lab prototype represented by its arena splash screen.",links:{},tech:[],caseStudy:"none",houseEligible:false,media:[capture("/portfolio/chart-colosseum.png","Chart Colleseum arena splash screen")]}),
 p({id:"deal-radar",slug:"deal-radar",name:"Deal Radar",category:"research",status:"scaffold",homepage:{section:"lab",order:3},hook:"A signal-finding experiment.",description:"A scaffold-stage deal-intelligence dashboard exploring leads, markets, and opportunity signals.",links:{},tech:[],caseStudy:"none",houseEligible:false,media:[capture("/portfolio/deal-radar.png","Deal Radar dashboard preview")]}),
 p({id:"crossword-builder",slug:"crossword-builder",name:"Crossword Builder",category:"research",status:"prototype",homepage:{section:"lab",order:4},hook:"A construction desk for wordplay.",description:"A thoughtful workspace for creating, refining, testing, and sharing crossword puzzles.",links:{},tech:[],caseStudy:"none",houseEligible:false,media:[capture("/portfolio/crossword-builder.png","Crossword Builder workspace preview")]}),
 p({id:"opportunity-fit",slug:"opportunity-fit",name:"Opportunity Fit",category:"research",status:"prototype",homepage:{section:"lab",order:5},hook:"Find the opportunity that fits the work.",description:"A command center for matching active projects, credentials, and application readiness to grants, scholarships, accelerators, and other opportunities.",links:{},tech:[],caseStudy:"none",houseEligible:false,media:[capture("/portfolio/opportunity-fit.png","Opportunity Fit dashboard preview")]}),

 ...(["Cooley’s Revenge","MOLT","Pilot City","You’re It","The Floor Is Negotiable","Corporate Espionage Sim","Life: A Horror Game","Kids at the Mall: ’97 Edition"] as const).map((name,index)=>p({id:["cooleys-revenge","molt","pilot-city","youre-it","room-negotiable","corporate-espionage-sim","life-horror-game","kid-at-mall"][index],slug:["cooleys-revenge","molt","pilot-city","youre-it","the-floor-is-negotiable","corporate-espionage-sim","life-horror-game","kid-at-the-mall"][index],name,category:"game",status:"concept",homepage:{section:"game-lab",order:index+1,featured:index===0},hook:"A Grey Key game concept.",description:`${name} is represented as concept work; no gameplay or finished media is implied.`,links:{},tech:[],caseStudy:"planned",houseEligible:true,media:[gameConcept(["/portfolio/cooleys-revenge.png","/portfolio/molt.png","/portfolio/pilot-city.png","/portfolio/youre-it.png","/portfolio/floor-is-negotiable.png","/portfolio/corporate-espionage-sim.png","/portfolio/life-horror-game.png","/portfolio/kid-at-the-mall.png"][index],`${name} concept art`)]})),
 p({id:"gk-backlot",slug:"gk-backlot",name:"GK Backlot",category:"worldbuilding",status:"prototype",homepage:{section:"game-lab",order:9},hook:"Reusable places waiting for stories.",description:"A supporting prototype and development system for Grey Key games.",links:{},tech:[],caseStudy:"planned",houseEligible:true,media:[gameConcept("/portfolio/gk-backlot.png","GK Backlot modular city concept art")],supporting:[{name:"Motel",label:"ENVIRONMENT SLOT"},{name:"Self-storage facility",label:"ENVIRONMENT SLOT"},{name:"Apartment",label:"ENVIRONMENT SLOT"},{name:"Radio station",label:"ENVIRONMENT SLOT"}]}),

 p({id:"bridge-academy",slug:"bridge-academy",name:"Bridge Academy",category:"education",status:"concept",homepage:{section:"bridge",order:1,featured:true},hook:"Build better builders.",description:"A proposed digital-first educational system connecting music, STEM, culture, entrepreneurship, hands-on projects, and career pathways.",links:{},tech:[],caseStudy:"planned",houseEligible:true,media:[{kind:"concept-art",provenance:"concept",readiness:"ready",label:"PLANNING WORKBENCH",alt:"Bridge Academy planning workbench with curriculum, music hardware, computing, electronics, historical material, and diagrams",src:"/portfolio/bridge-academy-hero.png",aspect:"16:10"}]}),
 p({id:"stack-house",slug:"stack-house",name:"The Stack House",category:"interactive",status:"in-development",homepage:{section:"stack-house",order:1,featured:true},hook:"The other door.",description:"A real-time house built for exploration, story, and the work that does not fit in a grid.",links:{internal:"/house"},tech:[],caseStudy:"planned",houseEligible:true,media:[{kind:"model",provenance:"real",readiness:"ready",label:"INTERACTIVE HOUSE MODEL",alt:"The Stack House interactive 3D model",src:"/models/house-main-optimized.glb",aspect:"16:9"}]}),
]

export const projectsFor=(section:HomepageSection)=>PORTFOLIO_PROJECTS.filter(x=>!x.held&&!x.archived&&x.homepage?.section===section).sort((a,b)=>(a.homepage!.order-b.homepage!.order))
export const SHIPPED_PROJECTS=projectsFor("work"), BUILDING_PROJECTS=projectsFor("building"), LAB_PROJECTS=projectsFor("lab"), GAME_PROJECTS=projectsFor("game-lab")
export const BRIDGE_PROJECT=projectsFor("bridge")[0], STACK_HOUSE_PROJECT=projectsFor("stack-house")[0]

export type IdentityTransition = "shutter" | "prism" | "film-burn" | "scanline" | "double-exposure" | "ink" | "signal"
export type IdentityAsset = { src?:string; alt:string; placeholder:string }
export interface MusicPreview {
  id:string; title:string; projectId?:string; audioSrc:string; artwork?:IdentityAsset
  sourceRef?:string; startSeconds?:number; endSeconds?:number
}
export interface MusicProject { id:string;title:string;artwork?:IdentityAsset;trackCandidates:string[];note?:string }
export interface MusicIdentity {
  id:string;name:string;descriptor:string;transition:IdentityTransition;basePortrait:IdentityAsset
  personaPortrait:IdentityAsset;logoFallback:IdentityAsset;artwork:IdentityAsset;audioLabel:string
  credits:string;projects:MusicProject[];previews:MusicPreview[];status:"identity-study"|"archive-ready";aside?:string
}
const baseMichael:IdentityAsset={alt:"Michael Walton base portrait",placeholder:"BASE PORTRAIT / MICHAEL WALTON"}
const artist=(src:string,alt:string,placeholder:string):IdentityAsset=>({src,alt,placeholder})
const projectArt=(src:string,alt:string,placeholder:string):IdentityAsset=>({src,alt,placeholder})
export const MUSIC_IDENTITIES:MusicIdentity[]=[
 {id:"mr-e",name:"Mr. E",descriptor:"Alias study · sonic identity",transition:"shutter",basePortrait:baseMichael,personaPortrait:artist("/portfolio/music/artists/mr-e.png","Mr. E persona portrait","MR. E / PERSONA PORTRAIT"),logoFallback:artist("/portfolio/music/artists/mr-e.png","Mr. E identity artwork","MR. E / IDENTITY"),artwork:projectArt("/portfolio/music/projects/destination-terra-gaia.png","Destination: Terra Gaia project artwork","DESTINATION: TERRA GAIA / PROJECT ARTWORK"),audioLabel:"Mr. E preview queue",credits:"Michael Walton · identity and music",projects:[
  {id:"builders-of-the-future",title:"Builders of the Future",trackCandidates:[],note:"Artwork and music selection TBD"},
  {id:"destination-terra-gaia",title:"Destination: Terra Gaia",artwork:projectArt("/portfolio/music/projects/destination-terra-gaia.png","Destination: Terra Gaia project artwork","DESTINATION: TERRA GAIA / PROJECT ARTWORK"),trackCandidates:["Lilas Lusty Lore","Starry Sojourn","Secure Comms"]},
  {id:"games-on-channel-3",title:"Games on Channel 3",artwork:projectArt("/portfolio/music/projects/games-on-channel-3.jpg","Games on Channel 3 project artwork","GAMES ON CHANNEL 3 / PROJECT ARTWORK"),trackCandidates:[],note:"Two-song project; preview selection TBD"},
 ],previews:[],status:"identity-study"},
 {id:"beautiful-uglies",name:"The Beautiful Uglies",descriptor:"Group identity · visual study",transition:"prism",basePortrait:baseMichael,personaPortrait:artist("/portfolio/music/artists/the-beautiful-uglies.png","The Beautiful Uglies group portrait","THE BEAUTIFUL UGLIES / GROUP PORTRAIT"),logoFallback:artist("/portfolio/music/artists/the-beautiful-uglies.png","The Beautiful Uglies identity artwork","THE BEAUTIFUL UGLIES / IDENTITY"),artwork:projectArt("/portfolio/music/projects/soundtrack-for-an-unmade-film.jpg","Soundtrack for an Unmade Film project artwork","SOUNDTRACK FOR AN UNMADE FILM / PROJECT ARTWORK"),audioLabel:"The Beautiful Uglies preview queue",credits:"Michael Walton · creative direction",projects:[
  {id:"soundtrack-for-an-unmade-film",title:"Soundtrack for an Unmade Film",artwork:projectArt("/portfolio/music/projects/soundtrack-for-an-unmade-film.jpg","Soundtrack for an Unmade Film project artwork","SOUNDTRACK FOR AN UNMADE FILM / PROJECT ARTWORK"),trackCandidates:[]},
  {id:"midnight-blues",title:"Midnight Blues",trackCandidates:["Midnight Blues 2","Midnight Blues","Tacit 2"],note:"Two additional selections and final artwork TBD"},
  {id:"a-series-of-failures",title:"A Series of Failures",artwork:projectArt("/portfolio/music/projects/a-series-of-failures.jpg","A Series of Failures project artwork","A SERIES OF FAILURES / PROJECT ARTWORK"),trackCandidates:["Toy 2"],note:"Additional selections TBD"},
  {id:"liminal-spaces",title:"Liminal Spaces (working title: 1317)",trackCandidates:["Abysmal","Space Race","Mango Mobile","Buffalo Roam"],note:"Title and visual identity still in development"},
 ],previews:[],status:"identity-study"},
 {id:"adwo-nyumbani",name:"Adwo Nyumbani",descriptor:"Alias study · character system",transition:"film-burn",basePortrait:baseMichael,personaPortrait:artist("/portfolio/music/artists/adwo-nyumbani.png","Adwo Nyumbani persona portrait","ADWO NYUMBANI / PERSONA PORTRAIT"),logoFallback:artist("/portfolio/music/artists/adwo-nyumbani.png","Adwo Nyumbani identity artwork","ADWO NYUMBANI / IDENTITY"),artwork:projectArt("/portfolio/music/projects/calm-home.jpg","Calm Home project artwork","CALM HOME / PROJECT ARTWORK"),audioLabel:"Adwo Nyumbani preview queue",credits:"Michael Walton · identity and music",projects:[
  {id:"calm-home",title:"Calm Home",artwork:projectArt("/portfolio/music/projects/calm-home.jpg","Calm Home project artwork","CALM HOME / PROJECT ARTWORK"),trackCandidates:[]},
  {id:"a-lamenting-waltz",title:"A Lamenting Waltz in C# Minor",trackCandidates:[],note:"Source music and artwork still need to be located"},
  {id:"abstract-waltz",title:"Abstract Waltz",artwork:projectArt("/portfolio/music/projects/abstract-waltz.jpg","Abstract Waltz project artwork","ABSTRACT WALTZ / PROJECT ARTWORK"),trackCandidates:["1899 Waltz"],note:"1899 Waltz features Mr. E"},
  {id:"the-golden-stool",title:"The Golden Stool",artwork:projectArt("/portfolio/music/projects/the-golden-stool.jpg","The Golden Stool project artwork","THE GOLDEN STOOL / PROJECT ARTWORK"),trackCandidates:["Homecoming"]},
 ],previews:[],status:"identity-study",aside:"Yes, this is still Michael. The aliases have begun organizing."},
 {id:"walton-grey",name:"Walton Grey",descriptor:"Alias study · tonal system",transition:"scanline",basePortrait:baseMichael,personaPortrait:artist("/portfolio/music/artists/walton-grey.png","Walton Grey persona portrait","WALTON GREY / PERSONA PORTRAIT"),logoFallback:artist("/portfolio/music/artists/walton-grey.png","Walton Grey identity artwork","WALTON GREY / IDENTITY"),artwork:projectArt("/portfolio/music/projects/private-karate.jpg","Private Karate project artwork","PRIVATE KARATE / PROJECT ARTWORK"),audioLabel:"Walton Grey preview queue",credits:"Michael Walton · identity and music",projects:[
  {id:"private-karate",title:"Private Karate",artwork:projectArt("/portfolio/music/projects/private-karate.jpg","Private Karate project artwork","PRIVATE KARATE / PROJECT ARTWORK"),trackCandidates:["OCB","Private Karate","Loungewear","Health","Mitchy Pitch","Hap Ness Monsta"]},
  {id:"plastic-horizons",title:"Plastic Horizons",artwork:projectArt("/portfolio/music/projects/plastic-horizons.jpg","Plastic Horizons project artwork","PLASTIC HORIZONS / PROJECT ARTWORK"),trackCandidates:["Jumpin Jack Flash","Sudsy OG","Forrest Spitaker"]},
  {id:"cardboard-portraits",title:"Cardboard Portraits",artwork:projectArt("/portfolio/music/projects/cardboard-portraits.jpg","Cardboard Portraits project artwork","CARDBOARD PORTRAITS / PROJECT ARTWORK"),trackCandidates:["Ive Come To Come","Smack Dab On The Eighth","My Stuff"]},
  {id:"lighthouse",title:"Lighthouse",trackCandidates:["Sunshine and Mangoes","False Nostalgia","Going Retro","King Of The Hill","Sweet Fading Mattress"],note:"Final artwork still required"},
 ],previews:[],status:"identity-study"},
 {id:"mic-titan",name:"Mic Titan",descriptor:"Alias study · performance identity",transition:"double-exposure",basePortrait:baseMichael,personaPortrait:artist("/portfolio/music/artists/mic-titan.png","Mic Titan persona portrait","MIC TITAN / PERSONA PORTRAIT"),logoFallback:artist("/portfolio/music/artists/mic-titan.png","Mic Titan identity artwork","MIC TITAN / IDENTITY"),artwork:artist("/portfolio/music/artists/mic-titan.png","Mic Titan identity artwork","MIC TITAN / PROJECT ARTWORK"),audioLabel:"Mic Titan preview queue",credits:"Michael Walton · identity and music",projects:[
  {id:"remix-projects",title:"Three remix projects",trackCandidates:[],note:"Approximately 2–4 representative remixes to be selected"},
  {id:"unreleased-collections",title:"Older unreleased collections",trackCandidates:[],note:"Approximately 2–3 collections and six representative beats to be selected"},
 ],previews:[],status:"identity-study"},
 {id:"chno",name:"CHNO",descriptor:"Generative music · signal identity",transition:"signal",basePortrait:baseMichael,personaPortrait:artist("/portfolio/music/artists/chno.png","CHNO persona portrait","CHNO / PERSONA PORTRAIT"),logoFallback:artist("/portfolio/music/artists/chno.png","CHNO identity artwork","CHNO / IDENTITY"),artwork:artist("/portfolio/music/artists/chno.png","CHNO identity artwork","CHNO / PROJECT ARTWORK"),audioLabel:"CHNO preview queue",credits:"Michael Walton · generative music identity",projects:[],previews:[],status:"identity-study",aside:"Music where generative AI is materially involved in creation, production, transformation, or performance."},
]
export const resolveMusicPreviewArtwork=(identity:MusicIdentity,preview:MusicPreview):IdentityAsset=>preview.artwork??identity.projects.find(project=>project.id===preview.projectId)?.artwork??identity.logoFallback
export const MUSIC_CREDITS=["Uncle Fart","The Bobby Backfat Band","Lemon Ice","Samon","Uncle Arctica","The Broken Shortcuts","Night Movers","Kief Swette"].map((name,index)=>({id:`credit-${index}`,name,descriptor:"Additional identity",artwork:{alt:`${name} identity artwork`,placeholder:`${name.toUpperCase()} / IDENTITY ART`} as IdentityAsset}))
