/**
 * Emits docs/stair-socket.md — the exact dimensions an art-asset staircase
 * must be built to.
 *
 * Run: npm run build:interior (this runs after the shell build)
 *
 * The rule is one-directional on purpose: the procedural system defines the
 * socket, the art asset fills it. Collision, traversal height and floor
 * transitions are all driven by these numbers, so a staircase modeled to
 * different dimensions would mean reshaping collision around the model —
 * exactly the coupling the generated shell exists to avoid.
 *
 * Generated rather than hand-written so it cannot drift from interior-layout.ts.
 */

const fs = require('fs')
const path = require('path')

const LAYOUT = path.join(__dirname, '..', '.interior-build', 'interior-layout.js')
const L = require(LAYOUT)
const { STAIRS, FLOOR_BASE_Y, CORE_MIN_X, CORE_MAX_X, CORE_Z0, CORE_Z1, TURN_Z, FLIGHT_W_MAX, FLIGHT_E_MIN, X0 } = L

const r = (n) => Math.round(n * 1000) / 1000

const flights = STAIRS.filter((s) => Math.abs(s.topY - s.bottomY) > 1e-6)
const f = flights[0]
const rise = Math.abs(f.topY - f.bottomY)
const run = Math.abs(f.topCoord - f.bottomCoord)
const pitch = (Math.atan(rise / run) * 180) / Math.PI

const lines = []
lines.push('# Stair socket spec')
lines.push('')
lines.push('**Generated by `scripts/stair-socket.cjs` — do not edit by hand.**')
lines.push('Regenerate with `npm run build:interior` after any layout change.')
lines.push('')
lines.push('The generated staircase in the interior GLBs is a **collision proxy**, not')
lines.push('artwork. Build the art asset to the dimensions below and it will drop onto the')
lines.push('proxy exactly. Do not reshape these to suit a model — collision, eye height and')
lines.push('floor transitions are all driven from them.')
lines.push('')
lines.push('## Shaft')
lines.push('')
lines.push('| | Value |')
lines.push('|---|---|')
lines.push(`| Shaft footprint (world X) | ${r(CORE_MIN_X)} → ${r(CORE_MAX_X)} (${r(CORE_MAX_X - CORE_MIN_X)} wide) |`)
lines.push(`| Shaft footprint (world Z) | ${r(CORE_Z0)} → ${r(CORE_Z1)} (${r(CORE_Z1 - CORE_Z0)} deep) |`)
lines.push(`| West flight, X band | ${r(CORE_MIN_X)} → ${r(FLIGHT_W_MAX)} (${r(FLIGHT_W_MAX - CORE_MIN_X)} wide) |`)
lines.push(`| East flight, X band | ${r(FLIGHT_E_MIN)} → ${r(CORE_MAX_X)} (${r(CORE_MAX_X - FLIGHT_E_MIN)} wide) |`)
lines.push(`| Newel gap between flights | ${r(FLIGHT_E_MIN - FLIGHT_W_MAX)} |`)
lines.push(`| Turn / half-landing Z | ${r(TURN_Z)} → ${r(CORE_Z1)} (${r(CORE_Z1 - TURN_Z)} deep) |`)
lines.push(`| House origin | X0 = ${X0}, front wall at Z = 0 |`)
lines.push('')
lines.push('## Flight')
lines.push('')
lines.push('| | Value |')
lines.push('|---|---|')
lines.push(`| Rise per flight | ${r(rise)} |`)
lines.push(`| Run per flight | ${r(run)} |`)
lines.push(`| Pitch | ${pitch.toFixed(1)}° |`)
lines.push(`| Floor-to-floor | ${r(FLOOR_BASE_Y.ground - FLOOR_BASE_Y.basement)} |`)
lines.push(`| Flights per storey | 2 (switchback, half-landing between) |`)
lines.push('')
lines.push('## Runs, per storey')
lines.push('')
lines.push('World Y. `bottomCoord`/`topCoord` are Z values and are **not** sorted —')
lines.push("a switchback's return leg runs toward −Z, so its topCoord is the smaller number.")
lines.push('')
lines.push('| id | floor | X band | Z: bottom → top | Y: bottom → top |')
lines.push('|---|---|---|---|---|')
for (const s of STAIRS) {
  const flat = Math.abs(s.topY - s.bottomY) < 1e-6
  lines.push(
    `| \`${s.id}\` | ${s.floor} | ${r(s.bounds.minX)} → ${r(s.bounds.maxX)} | ` +
    `${r(s.bottomCoord)} → ${r(s.topCoord)} | ${r(s.bottomY)} → ${r(s.topY)}${flat ? ' *(flat landing)*' : ''} |`
  )
}
lines.push('')
lines.push('## Rules for the art asset')
lines.push('')
lines.push('- Tread nosings must sit **on** the proxy surface, not above or below it. The')
lines.push('  player\'s eye is placed 1.7 above the interpolated surface height, so a model')
lines.push('  sitting proud of the proxy will read as walking through the treads.')
lines.push('- Railings, newels, balusters and stringers are **entirely art** — nothing in')
lines.push('  collision reads them, so they can be as ornate as the budget allows. They may')
lines.push('  overhang the shaft, but not into the walkable band of either flight.')
lines.push('- The shaft is a hole in every floor slab it passes through. A finished')
lines.push('  underside/soffit is the asset\'s job; the generator emits none.')
lines.push('- Model at world coordinates, or at origin with the offsets above applied on')
lines.push('  placement — either is fine, but state which.')
lines.push('')

const outDir = path.join(__dirname, '..', 'docs')
fs.mkdirSync(outDir, { recursive: true })
const out = path.join(outDir, 'stair-socket.md')
fs.writeFileSync(out, lines.join('\n'), 'utf8')
console.log(`\nstair-socket.md      ${flights.length} flights, ${pitch.toFixed(1)}° pitch  ->  docs/`)
