"use client"
import { createContext, useContext, useEffect, useRef, useState } from "react"
import { IdentityAsset, MUSIC_CREDITS, MUSIC_IDENTITIES, MusicIdentity } from "@/lib/portfolio-projects"

type PlayerState={identity:MusicIdentity|null;playing:boolean;select:(identity:MusicIdentity)=>void;toggle:()=>void}
const PlayerContext=createContext<PlayerState|null>(null)
function Asset({asset,className=""}:{asset:IdentityAsset;className?:string}){return asset.src?<img className={className} src={asset.src} alt={asset.alt}/>:<div className={`identity-placeholder ${className}`} role="img" aria-label={asset.alt}><span>{asset.placeholder}</span><i>MEDIA SLOT RESERVED</i></div>}
function MiniPlayer(){const p=useContext(PlayerContext)!;if(!p.identity)return null;return <aside className="identity-mini" aria-label="Persistent music preview"><button disabled={!p.identity.audioSrc} onClick={p.toggle} aria-label={p.identity.audioSrc?(p.playing?"Pause preview":"Play preview"):"Audio preview not yet available"}>{p.playing?"Ⅱ":"▶"}</button><div><b>{p.identity.name}</b><span>{p.identity.audioSrc?p.identity.audioLabel:"AUDIO SOURCE COMING"}</span></div><i/><time>—:—</time></aside>}
function IdentityPanel({identity,index,active,setActive}:{identity:MusicIdentity;index:number;active:boolean;setActive:()=>void}){const ref=useRef<HTMLElement>(null);const player=useContext(PlayerContext)!;const activate=()=>{setActive();player.select(identity)};useEffect(()=>{const node=ref.current;if(!node)return;const observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting&&entry.intersectionRatio>.52)activate()},{threshold:[.52]});observer.observe(node);return()=>observer.disconnect()},[identity.id]);return <article ref={ref} tabIndex={0} onFocus={activate} onClick={activate} onMouseEnter={activate} className={`identity-panel identity-panel--${identity.transition}${active?" is-active":""}`} aria-labelledby={`${identity.id}-title`}><div className="identity-panel__meta"><span>{String(index+1).padStart(2,"0")} / {String(MUSIC_IDENTITIES.length).padStart(2,"0")}</span><small>{identity.descriptor}</small></div><div className="identity-transform"><div className="identity-transform__base"><Asset asset={identity.basePortrait}/><label>MICHAEL WALTON</label></div><div className="identity-transform__persona"><Asset asset={identity.personaPortrait}/><label>{identity.name}</label></div><div className="identity-transform__seam"><span>BASE</span><i/><span>PERSONA</span></div></div><div className="identity-panel__copy"><div><span>IDENTITY TRANSFORMATION</span><h3 id={`${identity.id}-title`}>{identity.name}</h3>{identity.aside&&<p className="identity-aside">{identity.aside}</p>}<small>{identity.credits}</small><ul className="identity-projects" aria-label={`${identity.name} project titles`}>{identity.projectTitles.map(title=><li key={title}>{title}</li>)}</ul></div><div className="identity-art"><Asset asset={identity.artwork}/></div><button className="identity-play" disabled={!identity.audioSrc} onClick={(e)=>{e.stopPropagation();player.select(identity)}}><i>▶</i><span><b>{identity.audioSrc?"PLAY INSTRUMENTAL":"INSTRUMENTAL PREVIEW"}</b><small>{identity.audioSrc?identity.audioLabel:"AUDIO SOURCE COMING — PLAYER READY"}</small></span><time>—:—</time></button></div></article>}
function ClosingCredits(){const [slide,setSlide]=useState(0);const [paused,setPaused]=useState(false);const reduced=useRef(false);useEffect(()=>{reduced.current=matchMedia("(prefers-reduced-motion: reduce)").matches;if(reduced.current||paused)return;const timer=setInterval(()=>setSlide(v=>(v+1)%MUSIC_CREDITS.length),1750);return()=>clearInterval(timer)},[paused]);const move=(n:number)=>setSlide(v=>(v+n+MUSIC_CREDITS.length)%MUSIC_CREDITS.length);const credit=MUSIC_CREDITS[slide];return <div className="identity-credits" tabIndex={0} onMouseEnter={()=>setPaused(true)} onMouseLeave={()=>setPaused(false)} onFocus={()=>setPaused(true)} onBlur={()=>setPaused(false)} onKeyDown={e=>{if(e.key==="ArrowLeft")move(-1);if(e.key==="ArrowRight")move(1)}}><header><span>CLOSING CREDITS</span><p>And then there are the other names.</p></header><div className="identity-credits__stage" onTouchStart={()=>setPaused(true)}><Asset asset={credit.artwork}/><div><small>{String(slide+1).padStart(2,"0")} / {String(MUSIC_CREDITS.length).padStart(2,"0")}</small><h3>{credit.name}</h3><p>{credit.descriptor}</p></div></div><footer><button onClick={()=>move(-1)} aria-label="Previous identity">←</button><div>{MUSIC_CREDITS.map((x,i)=><button key={x.id} className={i===slide?"is-active":""} onClick={()=>setSlide(i)} aria-label={`Show ${x.name}`}/>)}</div><button onClick={()=>move(1)} aria-label="Next identity">→</button></footer></div>}
export function MusicIdentities(){const [active,setActive]=useState(0);const [selected,setSelected]=useState<MusicIdentity|null>(null);const [playing,setPlaying]=useState(false);const player:PlayerState={identity:selected,playing,select:(identity)=>{setSelected(identity);if(identity.audioSrc)setPlaying(true)},toggle:()=>{if(selected?.audioSrc)setPlaying(v=>!v)}};return <PlayerContext.Provider value={player}><section className="identities-section" id="music"><header className="identities-intro"><p>08 / GREY KEY · MUSIC</p><img src="/brand/greykey-lockup.svg" alt="Grey Key Studios"/><h2>One studio.<br/>One musician.<br/><em>A lot of aliases.</em></h2><div><b>MICHAEL WALTON</b><span>BASE IDENTITY / MINNEAPOLIS</span><p>The face at the center of a growing identity system. Scroll, focus, or tap to move through the cast.</p></div></header><div className="identity-sequence">{MUSIC_IDENTITIES.map((identity,index)=><IdentityPanel key={identity.id} identity={identity} index={index} active={index===active} setActive={()=>setActive(index)}/>)}</div><ClosingCredits/></section><MiniPlayer/></PlayerContext.Provider>}
